### PR TITLE
Update pom

### PR DESCRIPTION
**Pull request by joshgrantsauce**
Based on [this ticket](https://saucedev.atlassian.net/browse/SOL-2), I've updated some dependencies in the base pom and module pom files. I've also removed some outdated packages related to Selenium RC as Sauce no longer supports Selenium RC.

### CODE REVIEW

**Comment by titusfortner** [comment]
I ask in ignorance... You deleted jar files from the repo, is there a reason they were included in the first place?

**Comment by joshgrantsauce** [comment]
@titusfortner Good point. I deleted some directories related to using SeleniumRC (which Sauce does not support and the Selenium Project basically does not support) which included those jars. I wasn't aware there were jars kept there, but I can undo these deletions if needed and we can clean up this later.

**Comment by titusfortner** [comment]
if they were in an RC directory, they are likely fine to delete (I honestly don't know why jars were checked into the repo in the first place, instead of built locally from source code), but this also ties back into our other discussion of do we need to release something to maven central that marks these as dead projects before doing the delete.

**Comment by titusfortner** [comment]
ok, so this is just archetype stuff, in which case there is no maven issues.

But do we need the ant ones at all?

and shouldn't we also delete: `/quickstart-archetype/quickstart-seleniumrc-junit` directories with this PR?

**Pull request merged**
