### PR TITLE
Remove reference to SNAPSHOT in the testng/pom.xml

### PR DESCRIPTION
**Pull request by s3ck**
This was pointing to 2.1.21-SNAPSHOT - changed to point to 2.1.20

### CODE REVIEW

**Comment by moizjv** [comment]
@s3ck thanks for PR :) @halkeye want to review it and merge?

**Comment by moizjv** [comment]
@s3ck i think that is correctly pointing to 21-SNAPSHOT as it is for next release.

**Comment by s3ck** [comment]
@moizjv , shouldn't it point to the released dependency until the next release is out? As it is now, it will require a user to revert to 2.1.20 for maven to pull in the dependency or else it won't find it. Even if 2.1.21 is out - the Snapshot reference should be removed.

**Comment by moizjv** [comment]
@s3ck i see what you are saying, but its master branch. Tags are pointing correctly to published version https://github.com/saucelabs/sauce-java/tree/sauce_java-2.1.20.  Correct me if i am wrong

**Comment by s3ck** [comment]
I am looking at master: https://github.com/saucelabs/sauce-java/blob/master/pom.xml at line 6

**Comment by halkeye** [comment]
Wouldn't most people use https://maven-repository.com/artifact/com.saucelabs/sauce_testng/2.1.20 instead of the git repo directly?

**Comment by s3ck** [comment]
@halkeye yes.

**Comment by moizjv** [comment]
so if we compile `sauce_testng` individually it will error out as it won't find 2.1.20

```[INFO] ------------------------------------------------------------------------
[INFO] Building sauce_testng 2.1.21-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.saucelabs:sauce_java_common:jar:2.1.21-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.688 s
[INFO] Finished at: 2015-10-30T16:26:13-04:00
[INFO] Final Memory: 18M/981M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sauce_testng: Could not resolve dependencies for project com.saucelabs:sauce_testng:jar:2.1.21-SNAPSHOT: Could not find artifact com.saucelabs:sauce_java_common:jar:2.1.21-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException```

and if all snapshots are compiled together 

```[INFO] Reactor Summary:
[INFO] 
[INFO] sauce_java ......................................... SUCCESS [  0.133 s]
[INFO] sauce_java_common .................................. SUCCESS [  1.113 s]
[INFO] sauce_junit ........................................ SUCCESS [  0.064 s]
[INFO] sauce_testng ....................................... SUCCESS [  0.072 s]
[INFO] quickstart-archetype ............................... SUCCESS [  0.003 s]
[INFO] quickstart-seleniumrc-junit ........................ SUCCESS [  0.200 s]
[INFO] quickstart-seleniumrc-testng ....................... SUCCESS [  0.022 s]
[INFO] quickstart-webdriver-junit ......................... SUCCESS [  0.024 s]
[INFO] quickstart-webdriver-testng ........................ SUCCESS [  0.035 s]
[INFO] Sauce Connect Maven Plugin ......................... SUCCESS [  0.382 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.402 s
[INFO] Finished at: 2015-10-30T16:25:36-04:00
[INFO] Final Memory: 24M/981M
```

**Comment by s3ck** [comment]
Maybe things have changed but the testng/pom.xml was referencing a snapshot that was unavailable in the maven repo.

**Comment by moizjv** [comment]
you right @s3ck it wont be able to find it when build individually, i am wondering should we revert as suggested but since it is master we can add better instructions and keep it as is, so our testng uses latest version of `com.saucelabs:sauce_java_common:jar:2.1.21-SNAPSHOT`. I am open to fix as suggested and also other wise. What do you guys think?

**Comment by s3ck** [comment]
@moizjv Sounds good to me.

**Comment by moizjv** [comment]
i am open to change either ways :+1: ; what do you think @halkeye

**Comment by halkeye** [comment]
I have a feeling the maven release plugin updates all the submodule versions at the same time.

I think you need to build the parent and build them all at once, not just the testng one individually.

I'm still trying to ramp up on this code / maven releases.

**Comment by halkeye** [comment]
@s3ck do you have a usecase where you specifically need to build the testng jar but nothing else?

**Comment by s3ck** [comment]
@halkeye no. Other than when looking at that example project individually it could throw someone off a bit if they are not familiar with maven dependencies or how to use this example repro to get around it if they are doing it that way.

**Comment by saucyallison** [comment]
Hey Gavin! I'm a bit confused by the comments here, but wanted to offer my
help in case there's anything I can assist with. Feel free to ping me on
slack absolutely whenever! The Java interactions are dear to my heart and
many of our customers :D Otherwise, have a great weekend! Catch ya later!

Allison

**Comment by s3ck** [comment]
@halkeye, @saucyallison , @moizjv  I am going to go ahead and close this unless more people complain about it. Thanks.

**Pull request closed without merging**
